name = "modded boys server v6"
version = "1.2.0"
description = "Converted from Modrinth mrpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "935e7c6f54bf5337423ec8cd2d2c3c1e551537e5a7c49fd4a5003a9a3af7c8a4"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"
