name = "modded boys server v6"
version = "1.2.0"
description = "Converted from Modrinth mrpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a085aef64f3e414a3c4cd4a511388d20b4cbc76b6bfbecb8ba59a99cdabf21b"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"
