name = "modded boys server v6"
version = "1.2.0"
description = "Converted from Modrinth mrpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2891343b54bfd4a66cffaefcf4f48c753da3f9722c0819f5ad931bfae1cd6e1f"

[versions]
forge = "47.4.21"
minecraft = "1.20.1"
